# Generated by Django 5.2.7 on 2025-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_userchallenge_status_reflection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reflection',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='reflection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='mood',
            field=models.CharField(choices=[('H', 'Happy'), ('N', 'Netural'), ('S', 'Sad')], default='Netural', max_length=20),
        ),
    ]
