# Generated by Django 5.2.7 on 2025-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_content_reflection_text_reflection_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='mood',
            field=models.CharField(choices=[('H', 'Happy'), ('N', 'Netural'), ('S', 'Sad')], default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In progress'), ('C', 'Completed')], default='P', max_length=20),
        ),
    ]
