# Generated by Django 5.2.7 on 2025-10-29 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_reflection_mood_alter_userchallenge_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='challenge',
        ),
        migrations.AddField(
            model_name='reflection',
            name='user_challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.userchallenge'),
            preserve_default=False,
        ),
    ]
