# Generated by Django 5.2.7 on 2025-10-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_reflection_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflection',
            name='user',
        ),
    ]
